### PR TITLE
usercta has been added to the footer page

### PR DESCRIPTION
**Pull request by chegeMP**
footer page equipped with usercta

### CODE REVIEW

**Comment by chegeMP** [comment]
the user CTA can be used to allow users  add or input their feedback

**Comment by chegeMP** [comment]
user CTA has been added to allow users input their feedback on how they feel about the webapp

**Comment by Blackie360** [comment]
We need to do a code review.

**Review by Blackie360 — APPROVED** [review]
the userCTA  would be a button that opens two other new pages

**Pull request merged**
